apiVersion: v1
kind: Service
metadata:
  labels:    
    release: kubecon2017
    app: rbacissue
    component: frontend
  name: rbacissue-kubecon2017
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: rbacissue
    release: kubecon2017
    component: frontend
  type: ClusterIP
