apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:    
    release: kubecon2017
    app: imagepullerror
    component: frontend
  name: imagepullerror-frontend-kubecon2017
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imagepullerror
      release: kubecon2017
      component: frontend
  template:
    metadata:
      labels:        
        release: kubecon2017
        app: imagepullerror
        component: frontend
    spec:
      containers:
        - name: imagepullerror-frontend
          image: "weaveworks/scope:kubecon2017"
          imagePullPolicy: "IfNotPresent"
          args:
            - "--no-probe"
          ports:
            - name: http
              containerPort: 4040
              protocol: TCP
