apiVersion: v1
kind: Pod
metadata:
  name: mydb
  labels:
    name: mydb
spec:
  containers:
  - name: mydb
    image: mysql:5.7
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: redhat
    - name: MYSQL_USER
      value: tabish
    - name: MYSQL_PASS 
      value: redhat
    - name: MYSQL_DATABASE
      value: wpdb  