apiVersion: v1
kind: Pod
metadata:
  name: mywordpress
  labels:
    name: mywordpress
spec:
  containers:
  - name: mywordpress
    image: wordpress:5.1.1-php7.3-apache
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
