---
# Source: weave-scope/charts/weave-scope-agent/templates/daemonset.yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:    
    chart: weave-scope-agent-0.9.1
    heritage: Tiller
    release: kubecon2017
    app: weave-scope
    component: agent
  name: weave-scope-agent-kubecon2017
  annotations:    
    cloud.weave.works/launcher-info: |-
      {
        "server-version": "master-4fe8efe",
        "original-request": {
          "url": "/k8s/v1.7/scope.yaml"
        },
        "email-address": "support@weave.works",
        "source-app": "weave-scope",
        "weave-cloud-component": "scope"
      }
spec:
  selector:
    matchLabels:
      app: weave-scope
      release: kubecon2017
      component: agent
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:        
        chart: weave-scope-agent-0.9.1
        heritage: Tiller
        release: kubecon2017
        app: weave-scope
        component: agent
    spec:
      tolerations:
        - effect: NoSchedule
          operator: Exists
      containers:
        - name: weave-scope-agent
          image: "weaveworks/scope:1.6.5"
          imagePullPolicy: "IfNotPresent"
          args:
            - '--no-app'
            - '--probe.docker.bridge=docker0'
            - '--probe.docker=true'
            - '--probe.kubernetes=true'
            - kubecon2017.default.svc:80
          securityContext:
            privileged: true
          resources:
            null
            
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
            - name: scope-plugins
              mountPath: /var/run/scope/plugins
            - name: sys-kernel-debug
              mountPath: /sys/kernel/debug
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: scope-plugins
          hostPath:
            path: /var/run/scope/plugins
        - name: sys-kernel-debug
          hostPath:
            path: /sys/kernel/debug
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: kubecon2017-weave-scope
