---
# Source: weave-scope/charts/weave-scope-agent/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:    
    chart: weave-scope-agent-0.9.1
    heritage: Tiller
    release: kubecon2017
    app: weave-scope
    component: agent
  name: kubecon2017-weave-scope
  annotations:    
    cloud.weave.works/launcher-info: |-
      {
        "server-version": "master-4fe8efe",
        "original-request": {
          "url": "/k8s/v1.7/scope.yaml"
        },
        "email-address": "support@weave.works",
        "source-app": "weave-scope",
        "weave-cloud-component": "scope"
      }
