---
kind: Service
apiVersion: v1
metadata:
  name: my-service
spec:
  selector:
    app: flask-keras
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  externalIPs:
  - 172.31.12.245
