apiVersion: v1
kind: Service
metadata:
  labels:    
    release: kubecon2017
    app: discoveryfailure
    component: frontend
  name: discoveryfailure-kubecon2017
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: discoveryfailure
    release: kubecon2017
    component: frontend
  type: ClusterIP
