apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: mtabishk/apache2-php
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /var/www/html
        name: mypd
  volumes:
  - name: mypd
    persistentVolumeClaim: 
      claimName: mypvc
