apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:    
    release: kubecon2017
    app: rbacissue
    component: agent
  name: kubecon2017-rbacissue
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubecon2017-rbacissue
subjects:
  - kind: ServiceAccount
    name: kubecon2017-rbacissue-agent
    namespace: default
