apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: myweb-rs-sbs
spec:
  replicas: 3
  selector:
    matchExpressions:
    - { key: team, operator: In, values: [team1,team2]}
    - { key: tier, operator: In, values: [frontend]}
  template:
    metadata: 
      name: myweb-pod
      labels:
        env: prod
        team: team1
        tier: frontend
    spec:
      containers:
      - name: myweb-con
        image: mtabishk/apache2-php
  