apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: myd
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
   spec: 
    completions: 6
    parallelism: 2
    template:
      metadata:
        labels:
          app: myd
      spec:
        containers:
        - image: centos:7
          name: centos
          command:  [ "expr" ,  "2" ,  "+" ,  "4" ]
        restartPolicy: Never
