apiVersion: v1
kind: ReplicationController
metadata:
  name: webrc1
spec:
  replicas: 3
  selector:
    app: web
  template:
    metadata:
      name: mypod
      labels:
        app: web
    spec:
      containers:
        - name: mycon
          image: mtabishk/apache2-php
          ports:
            - containerPort: 80
